#spring:
#  data:
#    redis:
#      database: 6
#      host: 101.43.6.108
#      port: 6379
#      password: 'Ijdjh&234@jUy@.%tNxIkjsxy6hio.ua2'
#  datasource:
#    url: jdbc:mysql://101.43.6.108:3306/super_bot?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
#    username: root
#    password: 'Sjh@ii9A@jUy@.%tNxhio.ua23..@*7'
#
#
